name = "hono-react-cloudflare"
main = "server.ts"
compatibility_date = "2025-09-01"

[site]
bucket = "dist"

[build]
command = "pnpm run build"
cwd = "dist"
watch_dir = "src"

[observability]
enabled = true
head_sampling_rate = 1
