name = "hono-react-cloudflare"
main = "server.ts"
compatibility_date = "2023-09-20"

[site]
bucket = "dist"

[build]
command = "pnpm run build"
cwd = "dist"
watch_dir = "src"

[observability]
enabled = true
head_sampling_rate = 1

[env.production.vars]
API_ROOT = "hono-react-cloudflare.autumn-shadow-40fa.workers.dev"
